// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(schema, options) {
    var bcrypt;
    bcrypt = require('bcrypt');
    schema.add({
      email: {
        type: String,
        required: true,
        unique: true
      },
      password: {
        type: String,
        required: true
      }
    });
    schema.pre('save', function(next) {
      var _this = this;
      if (!this.isModified('password')) {
        return next();
      }
      return bcrypt.genSalt(10, function(err, salt) {
        if (err) {
          return next(err);
        }
        return bcrypt.hash(_this.password, salt, function(err, hash) {
          if (err) {
            return next(err);
          }
          _this.password = hash;
          return next();
        });
      });
    });
    return schema.methods.authenticate = function(password, callback) {
      return bcrypt.compare(password, this.password, function(err, valid) {
        if (err) {
          return callback(err);
        }
        if (valid) {
          return callback(null, true);
        }
        return callback(null, false);
      });
    };
  };

}).call(this);
